version_0.0.4
appvinio/any_animated_button pull request #5
Opened 2022-10-20 08:12 UTC by libsonnAppvinio

- Updated CHANGELOG.md
- Updated README.md
- updated flutter version to use 3.3.5
- added child field `AnyAnimatedButtonBlocListener` to make it usable without MultiBlocListener

2022-10-20 08:29 UTC, Filiponesco requested changes

2022-10-20 08:29 UTC, Filiponesco commented on example/lib/buttons/minimalistic_button.dart
> +  }) : super();
przesłać klucz do CustomAnyAnimatedButton

2022-10-20 08:29 UTC, Filiponesco commented on example/lib/buttons/pretty_button.dart
> +  }) : super();
`: super(key: key);`

2022-10-26 11:11 UTC, rafaldziuryk approved these changes

2022-10-26 11:11 UTC, merged